### ISSUE TITLE
Create multiple tags for docker image

### ISSUE THREAD

**Issue by cwpearson** [rai-project/rai#21]
We could change the rai_build.yml format to accept something like:

```yaml
rai:
  version: 0.2
commands:
  build_image:
    image_name: 
      - c3sr/celery:4.0.2
      - c3sr/celery:latest
    dockerfile: "./Dockerfile"
    push:
      push: true
      credentials:
        username: dakkak
        password: ==AES32==PASS
```

multiple names under the `commands.build_image.image_name` field, instead of just a single one
